#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
WINDOWS=0
case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) WINDOWS=1 ;; esac
MODE=""
GROUP_LIBRARY=0
ADVANCED=0
export PAPER2ZOTERO_AGENT="${PAPER2ZOTERO_AGENT:-auto}"
while (( $# )); do
  case "$1" in
    --help)
      echo 'Usage: bash install/setup.sh [--demo | --demo-missing | --dependencies-only | --check] [--advanced] [--group] [--agent auto|codex|claude-code|pi|all]'
      exit 0 ;;
    --group) GROUP_LIBRARY=1 ;;
    --advanced) ADVANCED=1 ;;
    --agent)
      [[ $# -ge 2 ]] || { echo '--agent needs a value' >&2; exit 2; }
      PAPER2ZOTERO_AGENT="$2"; shift ;;
    --dependencies-only|--check|--demo|--demo-missing)
      [[ -z "$MODE" ]] || { echo 'Choose one setup mode' >&2; exit 2; }
      MODE="$1" ;;
    *) echo 'Unknown option; use --help' >&2; exit 2 ;;
  esac
  shift
done
case "$PAPER2ZOTERO_AGENT" in auto|codex|claude-code|pi|all) ;; *) echo 'Unknown agent; use --help' >&2; exit 2;; esac
if [[ "$MODE" == --dependencies-only || "$MODE" == --check ]]; then
  exec bash "$SKILL_DIR/scripts/bootstrap.sh" "$MODE"
fi
if [[ "$ADVANCED" == 1 ]]; then TOTAL_STAGES=7; fi
# The library remains verbatim. Setup-specific behavior lives below STAGES.
umask 077
ENV_FILE="$HOME/.config/literature-to-zotero/env"
DEMO=0
if [[ "$MODE" == --demo* ]]; then
  DEMO=1
  DEMO_DIR="$(mktemp -d)"
  trap 'rm -rf "$DEMO_DIR"' EXIT
  ENV_FILE="$DEMO_DIR/env"
  cat > "$ENV_FILE" <<'DEMOENV'
ZOTERO_API_KEY=demo-zotero-key
ZOTERO_LIBRARY_TYPE=user
ZOTERO_LIBRARY_ID=12345678
MINERU_TOKEN=demo-mineru-token
DEMOENV
  open_url() { note "[模拟打开网页] $1"; }
else
  [[ -t 0 ]] || { echo '请在交互终端运行 setup；Agent 可先用 --dependencies-only。'; exit 2; }
fi
persist() {
  local key="$1" value="$2"
  [[ -n "$value" ]] || return 0
  if [[ "$DEMO" == 1 ]]; then
    write_env "$key" "$value" >/dev/null
  else
    printf '%s' "$value" | "$PYTHON_BIN" "$SKILL_DIR/scripts/configure.py" --set "$key"
  fi
  export "$key=$value"
}
verify_step() {
  if [[ "$DEMO" == 1 ]]; then note '[模拟检查通过，未连接服务]'; return 0; fi
  "$PYTHON_BIN" "$SKILL_DIR/scripts/configure.py" --verify "$1"
}
existing_ok() {
  [[ "$DEMO" == 0 ]] || return 1
  "$PYTHON_BIN" "$SKILL_DIR/scripts/verify.py" "$1" >/dev/null 2>&1
}
guide() {
  if [[ "$DEMO" == 0 ]]; then
    "$PYTHON_BIN" - "$SKILL_DIR/scripts" "$1" <<'PY'
import sys
sys.path.insert(0, sys.argv[1])
import capability
print(capability.GUIDE[sys.argv[2]]['do'])
PY
  fi
}

_clear
printf '\n%s%s  把论文和阅读笔记放进 Zotero%s\n\n' "$BOLD" "$BLUE" "$RESET"
say '工具由安装器准备；你只需要登录账号，复制网页上的授权码。'
say '第一次主要连接两个账号。暂时没有也可以跳过，之后继续。'
note '输入授权码时屏幕不会显示字符，这是正常的。Ctrl-C 可退出，已保存内容会保留。'
if [[ "$ADVANCED" == 1 ]]; then note '已打开更多设置：检索来源、电脑同步、浏览器全文。'; fi
pause '按回车开始'

if [[ "$DEMO" == 1 ]]; then
  warn '演示模式：不安装软件、不打开网页、不连接服务。配置仅写入临时目录，退出即删除。'
  note '密钥直接回车使用示例；请勿输入真实密钥。'
  pause '回车开始体验'
fi

stage "准备工具和 AI 助手"
if [[ "$DEMO" == 1 ]]; then
  bash "$SKILL_DIR/scripts/bootstrap.sh" --probe
  if [[ "$MODE" == --demo-missing ]]; then
    note '[模拟新电脑] 缺少 Python / Poppler → 安装缺少项 → 再次验证。'
  else
    note '以上为本机只读检查。缺失项在正式安装时自动补齐。'
  fi
else
  bash "$SKILL_DIR/scripts/bootstrap.sh" --runtime-only
  IFS= read -r PYTHON_BIN < "$HOME/.config/literature-to-zotero/python-path"
  if [[ "$WINDOWS" == 1 ]]; then PYTHON_BIN="$(cygpath -u "$PYTHON_BIN")"; fi
  export PYTHON_BIN
fi
if [[ "$DEMO" == 1 ]]; then
  note '[模拟安装] 连接所选 AI 助手，工具保存到固定位置。'
else
  if ! "$PYTHON_BIN" "$SKILL_DIR/scripts/install.py" --detect; then
    say '你要在哪个 AI 助手中使用？1 = Codex，2 = Claude Code，3 = Pi'
    while true; do
      printf '  输入 1、2 或 3：'
      IFS= read -r AGENT_CHOICE || { note '配置已暂停，重跑向导可继续。'; exit 130; }
      case "$AGENT_CHOICE" in
        1) PAPER2ZOTERO_AGENT=codex; break ;;
        2) PAPER2ZOTERO_AGENT=claude-code; break ;;
        3) PAPER2ZOTERO_AGENT=pi; break ;;
        *) warn '请选择一个助手。' ;;
      esac
    done
  fi
  bash "$SKILL_DIR/scripts/install-skill.sh"
fi
pause '准备完成，回车连接 Zotero'

stage "连接 Zotero：保存你的论文"
say 'Zotero 是保存和整理文献的工具。这一步允许助手把论文和笔记存入你的账号。'
say '授权码相当于给这个工具的一把专用钥匙；不要填写账号密码。'
if [[ "$GROUP_LIBRARY" == 0 ]] && existing_ok zotero-key; then
  note '✓ 已有凭据通过验证，跳过填写。'
else
  open_url 'https://www.zotero.org/settings/keys'
  step '1. 登录 Zotero；还没有账号，可先在网页上注册。'
  step '2. 点击 Create new private key / New Key，新建一个授权码，名称填 paper2zotero。'
  step '3. 个人文库勾选 Allow library access、Allow notes access、Allow write access，然后保存。'
  if [[ "$GROUP_LIBRARY" == 1 ]]; then step '你选择了群组文库：还需要允许目标群组的读取和写入。'; fi
  step '4. 复制刚生成的 Key，粘贴到下方。'
  ask_secret ZOTERO_API_KEY '粘贴 Zotero 授权码（回车保留已有值；没有则稍后再配）：'
  persist ZOTERO_API_KEY "$ZOTERO_API_KEY"
  ZOTERO_LIBRARY_TYPE="${ZOTERO_LIBRARY_TYPE:-$(_existing ZOTERO_LIBRARY_TYPE || true)}"
  ZOTERO_LIBRARY_TYPE="${ZOTERO_LIBRARY_TYPE:-user}"
  if [[ "$GROUP_LIBRARY" == 1 ]]; then ZOTERO_LIBRARY_TYPE=group; fi
  [[ "$ZOTERO_LIBRARY_TYPE" == user || "$ZOTERO_LIBRARY_TYPE" == group ]] || { warn '已有文库类型无效，请检查配置。'; exit 1; }
  persist ZOTERO_LIBRARY_TYPE "$ZOTERO_LIBRARY_TYPE"
  if [[ "$ZOTERO_LIBRARY_TYPE" == user ]]; then note '默认保存到你自己的 Zotero。'; fi
  if [[ -n "$ZOTERO_API_KEY" ]]; then
    LIBID=''
    if [[ "$ZOTERO_LIBRARY_TYPE" == user ]]; then
      if [[ "$DEMO" == 1 ]]; then
        LIBID=12345678
      else
        LIBID="$(ZOTERO_API_KEY="$ZOTERO_API_KEY" "$PYTHON_BIN" "$SKILL_DIR/scripts/verify.py" self-id 2>/dev/null || true)"
        [[ "$LIBID" =~ ^[0-9]+$ ]] || LIBID=''
      fi
    fi
    if [[ -n "$LIBID" ]]; then
      persist ZOTERO_LIBRARY_ID "$LIBID"
      note '✓ 已自动找到你的个人文库。'
    else
      ask ZOTERO_LIBRARY_ID '未自动取得文库 ID，可填写或回车稍后配置：'
      [[ -z "$ZOTERO_LIBRARY_ID" || "$ZOTERO_LIBRARY_ID" =~ ^[0-9]+$ ]] || { warn '文库 ID 应为数字。'; exit 1; }
      persist ZOTERO_LIBRARY_ID "$ZOTERO_LIBRARY_ID"
    fi
    verify_step zotero-key || warn '凭据尚未通过验证；已填写内容保留，可重跑修复。'
  else
    note '已跳过 Zotero 凭据；检索仍可使用，写入文库需稍后补齐。'
  fi
fi
pause '按回车继续'

stage "启用全文阅读：整理 PDF"
say '这一步使用 MinerU，把论文 PDF 转成适合阅读和总结的文字，也能识别扫描页。'
say '它是独立的在线服务，需要另一个账号；下面会打开注册和授权页面。'
note '配置时不上传论文。以后处理时，助手会说明论文将上传到 MinerU，并取得你的许可。'
note '暂时跳过仍可检索和保存 PDF；格式化阅读材料需要以后补齐。'
if existing_ok mineru; then
  note '✓ 已有授权通过验证，跳过填写。'
else
  open_url 'https://mineru.net/apiManage/token'
  step '1. 登录或注册 MinerU。'
  step '2. 在 API 管理页面创建 Token（授权码），名称可填 paper2zotero。'
  step '3. 复制刚生成的完整授权码，粘贴到下方。'
  note '页面上的 API / Token 是网站使用的名称，你不需要编写代码。'
  ask_secret MINERU_TOKEN '粘贴全文阅读授权码（回车保留已有值；没有则稍后再配）：'
  persist MINERU_TOKEN "$MINERU_TOKEN"
  if [[ -n "$MINERU_TOKEN" ]]; then
    verify_step mineru || warn '授权尚未通过验证；可以稍后重试。'
  else
    note '已跳过；需要格式化阅读材料时，再来连接这个账号。'
  fi
fi
pause '按回车继续'

if [[ "$ADVANCED" == 1 ]]; then
stage "更多设置：补充检索来源"
say '默认跳过，直接回车即可；仍可检索，部分来源覆盖或请求额度可能减少。'
if confirm '现在填写检索增强配置'; then
  say '这些都是额外的文献来源。没有授权码就跳过，不用现在逐个注册。'
  if confirm '已有 OpenAlex 授权码，或需要打开申请页面'; then
    note 'OpenAlex 提供论文题录；服务额度以账号页面为准。'
    open_url 'https://openalex.org'
    ask_secret OPENALEX_API_KEY 'OpenAlex 授权码（可留空）：'
    persist OPENALEX_API_KEY "$OPENALEX_API_KEY"
  fi
  if confirm '已有 Semantic Scholar 授权码，或需要打开申请页面'; then
    note 'Semantic Scholar 是另一个学术搜索服务，可补充论文与引用信息。申请可能需要等待。'
    open_url 'https://www.semanticscholar.org/product/api'
    ask_secret SEMANTIC_SCHOLAR_API_KEY 'Semantic Scholar 授权码（可留空）：'
    persist SEMANTIC_SCHOLAR_API_KEY "$SEMANTIC_SCHOLAR_API_KEY"
  fi
  if confirm '用联系邮箱启用 Crossref 的友好访问'; then
    note 'Crossref 提供论文题录；邮箱随查询发送给 Crossref，用于联系，不需要邮箱密码。'
    ask CROSSREF_MAILTO '联系邮箱（可留空）：'
    persist CROSSREF_MAILTO "$CROSSREF_MAILTO"
  fi
  if confirm '用联系邮箱启用 Unpaywall 免费全文查找'; then
    note 'Unpaywall 帮助定位合法开放的全文；邮箱随查询发送给该服务。'
    ask UNPAYWALL_EMAIL '联系邮箱（可留空）：'
    persist UNPAYWALL_EMAIL "$UNPAYWALL_EMAIL"
  fi
else
  note '已跳过；已有配置保留。'
fi
pause '按回车继续'

stage "更多设置：在电脑上阅读附件"
if confirm '现在配置电脑上的 Zotero，让附件自动下载'; then
  persist SETUP_DESKTOP 1
  if [[ "$DEMO" == 1 ]]; then
    note '[模拟] 检查/安装 Zotero Desktop 并启动。'
  elif [[ "$(uname -s)" == Darwin ]]; then
    if [[ ! -d /Applications/Zotero.app && ! -d "$HOME/Applications/Zotero.app" ]]; then
      if command -v brew >/dev/null 2>&1; then brew install --cask zotero; else open_url 'https://www.zotero.org/download'; fi
    fi
    open -a Zotero || true
  elif [[ "$WINDOWS" == 1 ]]; then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(cygpath -w "$SKILL_DIR/scripts/windows-zotero.ps1")" || warn '请从开始菜单打开 Zotero，或重跑安装。'
  else
    open_url 'https://www.zotero.org/download'
  fi
  step '登录 Zotero；在设置中开启本地 API、附件同步与自动下载。'
  guide zotero_local
  guide zotero_sync
  pause '完成后回车检查'
  verify_step zotero-local || warn 'Desktop 尚未连接。'
  verify_step zotero-sync || warn '附件同步尚未就绪。'
else
  note '跳过本次配置；云端写入不依赖 Desktop。'
fi
pause '按回车继续'

stage "更多设置：通过学校或机构获取全文"
say '如果需要在已登录的浏览器中下载论文，可以连接浏览器扩展。'
note '只下载直接公开的全文，可以跳过。'
if confirm '现在连接浏览器（使用 Kimi 扩展）'; then
  persist SETUP_BROWSER 1
  if [[ "$DEMO" == 1 ]]; then
    note '[模拟] 检查 daemon，缺失则安装，然后启动。'
  else
    KIMI_BIN="$(command -v kimi-webbridge || true)"
    KIMI_BIN="${KIMI_BIN:-$HOME/.kimi-webbridge/bin/kimi-webbridge}"
    if [[ "$WINDOWS" == 1 && -x "$HOME/.kimi-webbridge/bin/kimi-webbridge.exe" ]]; then KIMI_BIN="$HOME/.kimi-webbridge/bin/kimi-webbridge.exe"; fi
    if [[ "$WINDOWS" == 1 && ! -x "$KIMI_BIN" ]]; then
      open_url 'https://www.kimi.com/products/kimi-webbridge'
      step '按页面的 Windows 安装说明安装连接服务。'
      pause '安装完成后回车'
      KIMI_BIN="$HOME/.kimi-webbridge/bin/kimi-webbridge.exe"
    elif [[ ! -x "$KIMI_BIN" ]]; then
      installer="$(mktemp)"
      if curl -fsSL https://cdn.kimi.com/webbridge/install.sh -o "$installer"; then bash "$installer"; fi
      rm -f "$installer"
    fi
    "$KIMI_BIN" start || warn '连接服务尚未启动，稍后可重跑配置。'
  fi
  open_url 'https://www.kimi.ai/products/kimi-webbridge'
  step '安装并启用浏览器扩展，授权连接；机构访问还需登录机构账号。'
  pause '完成后回车检查'
  verify_step kimi || warn '浏览器尚未连接。'
else
  note '已跳过；可直接下载的全文不需要浏览器。'
fi
pause '按回车继续'

fi

stage "检查结果，开始使用"
if [[ "$DEMO" == 1 ]]; then
  note '[模拟检查通过] 正式版会验证核心服务及选中的可选功能。'
  pause '回车查看演示结果'
  _clear
  say '✓ 配置演示结束。'
  warn '以上结果均为模拟，不代表真实环境就绪；临时配置即将删除。'
else
  if "$PYTHON_BIN" "$SKILL_DIR/scripts/configure.py" --check; then
    pause '检查通过，回车查看结果'
    _clear
    say '✓ 配置完成。回到你的 AI 助手，试着说：'
    say '“帮我找近三年 AI 心理健康干预的研究，先给我一份候选清单。”'
    note '如果暂时找不到技能，新开一个助手会话再试。'
    note '以后需要更多设置，可以让助手“打开文献工具的更多设置”。'
  else
    warn '部分配置尚未完成；已填写内容保留，重跑 setup 即可继续。'
    exit 1
  fi
fi

say '总结提示词可以换成你更熟悉的版本，保留默认也可以直接使用。'
if confirm '想换用自己的总结提示词？查看需要修改的文件位置'; then
  say '需要修改的文件：'
  if [[ "$DEMO" == 1 ]]; then
    note '[演示路径] <当前助手的 literature-to-zotero 目录>/references/paper-summary.md'
  else
    "$PYTHON_BIN" - "$SKILL_DIR/scripts" "$PAPER2ZOTERO_AGENT" <<'PY'
import sys
from pathlib import Path
sys.path.insert(0, sys.argv[1])
from agent_installation import installed_paths
paths = dict.fromkeys(str((Path(root) / 'references' / 'paper-summary.md').resolve())
                      for root in installed_paths(agent=sys.argv[2]))
for path in paths:
    print('  ' + path)
if not paths:
    print('  在当前助手实际加载的 literature-to-zotero 目录中，找到 references/paper-summary.md。')
PY
  fi
  step '用文本编辑器打开该 Markdown 文件，将开头的阅读分析要求换成自己的提示词。'
  step '保留“## Save and continue”及之后的保存、续跑说明；无需修改账号配置。'
  note '保存后在新文献任务中使用；已有笔记不会自动重写。更新或重装可能覆盖文件，请自行保留自定义提示词副本。'
  note '这里只提供修改位置，不打开编辑器、不修改文件。'
fi
