#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
WINDOWS=0
case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) WINDOWS=1 ;; esac
MODE="${1:-}"
GROUP_LIBRARY=0
if [[ "$MODE" == --group ]]; then GROUP_LIBRARY=1; MODE=""; fi
case "$MODE" in
  --help) echo 'Usage: bash setup.sh [--demo | --demo-missing | --dependencies-only | --check | --group]'; exit 0 ;;
  --dependencies-only|--check) exec bash "$SKILL_DIR/scripts/bootstrap.sh" "$MODE" ;;
  ''|--demo|--demo-missing) ;;
  *) echo 'Unknown option; use --help' >&2; exit 2 ;;
esac
# The library remains verbatim. Setup-specific behavior lives below STAGES.
umask 077
ENV_FILE="$HOME/.config/literature-to-zotero/env"
DEMO=0
if [[ "$MODE" == --demo* ]]; then
  DEMO=1
  DEMO_DIR="$(mktemp -d)"
  trap 'rm -rf "$DEMO_DIR"' EXIT
  ENV_FILE="$DEMO_DIR/env"
  cat > "$ENV_FILE" <<'DEMOENV'
ZOTERO_API_KEY=demo-zotero-key
ZOTERO_LIBRARY_TYPE=user
ZOTERO_LIBRARY_ID=12345678
MINERU_TOKEN=demo-mineru-token
DEMOENV
  open_url() { note "[模拟打开网页] $1"; }
else
  [[ -t 0 ]] || { echo '请在交互终端运行 setup；Agent 可先用 --dependencies-only。'; exit 2; }
fi
persist() {
  local key="$1" value="$2"
  [[ -n "$value" ]] || return 0
  mkdir -p "$(dirname "$ENV_FILE")"
  write_env "$key" "$value"
  chmod 600 "$ENV_FILE"
  if [[ "$WINDOWS" == 1 && "$DEMO" == 0 ]]; then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(cygpath -w "$SKILL_DIR/scripts/protect-config.ps1")" -ConfigPath "$(cygpath -w "$ENV_FILE")"
  fi
  export "$key=$value"
}
verify_step() {
  if [[ "$DEMO" == 1 ]]; then note '[模拟检查通过，未连接服务]'; return 0; fi
  "$PYTHON_BIN" "$SKILL_DIR/scripts/verify.py" "$1"
}
existing_ok() {
  [[ "$DEMO" == 0 ]] || return 1
  "$PYTHON_BIN" "$SKILL_DIR/scripts/verify.py" "$1" >/dev/null 2>&1
}
guide() {
  if [[ "$DEMO" == 0 ]]; then
    "$PYTHON_BIN" - "$SKILL_DIR/scripts" "$1" <<'PY'
import sys
sys.path.insert(0, sys.argv[1])
import capability
print(capability.GUIDE[sys.argv[2]]['do'])
PY
  fi
}

banner "literature-to-zotero 环境向导"
if [[ "$DEMO" == 1 ]]; then
  warn '演示模式：不安装软件、不打开网页、不连接服务。配置仅写入临时目录，退出即删除。'
  note '密钥直接回车使用示例；请勿输入真实密钥。'
  pause '回车开始体验'
fi

stage "检查 Python 与 Poppler"
if [[ "$DEMO" == 1 ]]; then
  bash "$SKILL_DIR/scripts/bootstrap.sh" --probe
  if [[ "$MODE" == --demo-missing ]]; then
    note '[模拟新电脑] 缺少 Python / Poppler → 安装缺少项 → 再次验证。'
  else
    note '以上为本机只读检查。缺失项在正式安装时自动补齐。'
  fi
else
  bash "$SKILL_DIR/scripts/bootstrap.sh" --runtime-only
  IFS= read -r PYTHON_BIN < "$HOME/.config/literature-to-zotero/python-path"
  if [[ "$WINDOWS" == 1 ]]; then PYTHON_BIN="$(cygpath -u "$PYTHON_BIN")"; fi
  export PYTHON_BIN
fi
pause '依赖检查完成，回车继续'

stage "安装 skill"
if [[ "$DEMO" == 1 ]]; then
  note '[模拟安装] 保存到固定位置，再连接 Codex / Pi / Claude Code。'
else
  bash "$SKILL_DIR/scripts/install-skill.sh"
fi
pause '回车配置账号'

stage "Zotero 读写密钥"
if [[ "$GROUP_LIBRARY" == 0 ]] && existing_ok zotero-key; then
  note '✓ 已有凭据通过验证，跳过填写。'
else
  open_url 'https://www.zotero.org/settings/keys'
  step '创建允许目标文库读写的 key，并复制到下方；暂时没有可以直接回车。'
  ask_secret ZOTERO_API_KEY 'Zotero key（回车保留已有值，没有则暂时跳过）：'
  persist ZOTERO_API_KEY "$ZOTERO_API_KEY"
  ZOTERO_LIBRARY_TYPE="${ZOTERO_LIBRARY_TYPE:-$(_existing ZOTERO_LIBRARY_TYPE || true)}"
  ZOTERO_LIBRARY_TYPE="${ZOTERO_LIBRARY_TYPE:-user}"
  if [[ "$GROUP_LIBRARY" == 1 ]]; then ZOTERO_LIBRARY_TYPE=group; fi
  [[ "$ZOTERO_LIBRARY_TYPE" == user || "$ZOTERO_LIBRARY_TYPE" == group ]] || { warn '已有文库类型无效，请检查配置。'; exit 1; }
  persist ZOTERO_LIBRARY_TYPE "$ZOTERO_LIBRARY_TYPE"
  if [[ "$ZOTERO_LIBRARY_TYPE" == user ]]; then note '使用个人文库（默认），无需填写文库类型。'; fi
  if [[ -n "$ZOTERO_API_KEY" ]]; then
    LIBID=''
    if [[ "$ZOTERO_LIBRARY_TYPE" == user ]]; then
      if [[ "$DEMO" == 1 ]]; then
        LIBID=12345678
      else
        LIBID="$(ZOTERO_API_KEY="$ZOTERO_API_KEY" "$PYTHON_BIN" "$SKILL_DIR/scripts/verify.py" self-id 2>/dev/null || true)"
        [[ "$LIBID" =~ ^[0-9]+$ ]] || LIBID=''
      fi
    fi
    if [[ -n "$LIBID" ]]; then
      persist ZOTERO_LIBRARY_ID "$LIBID"
      note "已自动取得文库 ID：$LIBID"
    else
      ask ZOTERO_LIBRARY_ID '未自动取得文库 ID，可填写或回车稍后配置：'
      [[ -z "$ZOTERO_LIBRARY_ID" || "$ZOTERO_LIBRARY_ID" =~ ^[0-9]+$ ]] || { warn '文库 ID 应为数字。'; exit 1; }
      persist ZOTERO_LIBRARY_ID "$ZOTERO_LIBRARY_ID"
    fi
    verify_step zotero-key || warn '凭据尚未通过验证；已填写内容保留，可重跑修复。'
  else
    note '已跳过 Zotero 凭据；检索仍可使用，写入文库需稍后补齐。'
  fi
fi
pause

stage "MinerU 解析凭据"
if existing_ok mineru; then
  note '✓ 已有 token 通过验证，跳过填写。'
else
  open_url 'https://mineru.net/apiManage/token'
  step '登录后在 API 管理页面创建并复制 token。'
  ask_secret MINERU_TOKEN 'MinerU token（回车保留已有值，没有则暂时跳过）：'
  persist MINERU_TOKEN "$MINERU_TOKEN"
  if [[ -n "$MINERU_TOKEN" ]]; then
    verify_step mineru || warn 'token 尚未通过验证；可稍后重跑。'
  else
    note '已跳过 MinerU；全文解析需稍后补齐 token。'
  fi
fi
pause

stage "可选检索增强"
say '默认跳过，直接回车即可；仍可检索，部分来源覆盖或请求额度可能减少。'
if confirm '现在填写检索增强配置'; then
  open_url 'https://openalex.org'
  ask_secret OPENALEX_API_KEY 'OpenAlex API key（可留空）：'
  persist OPENALEX_API_KEY "$OPENALEX_API_KEY"
  open_url 'https://www.semanticscholar.org/product/api'
  ask_secret SEMANTIC_SCHOLAR_API_KEY 'Semantic Scholar API key（可留空）：'
  persist SEMANTIC_SCHOLAR_API_KEY "$SEMANTIC_SCHOLAR_API_KEY"
  open_url 'https://www.crossref.org/documentation/retrieve-metadata/rest-api/'
  ask CROSSREF_MAILTO 'Crossref 联系邮箱（不是 API key；可留空）：'
  persist CROSSREF_MAILTO "$CROSSREF_MAILTO"
  open_url 'https://unpaywall.org/products/api'
  ask UNPAYWALL_EMAIL 'Unpaywall 联系邮箱（启用开放全文定位；可留空）：'
  persist UNPAYWALL_EMAIL "$UNPAYWALL_EMAIL"
else
  note '已跳过；已有配置保留。'
fi
pause

stage "可选：Zotero Desktop 本地同步"
if confirm '需要在 Desktop 中自动下载并核验附件'; then
  persist SETUP_DESKTOP 1
  if [[ "$DEMO" == 1 ]]; then
    note '[模拟] 检查/安装 Zotero Desktop 并启动。'
  elif [[ "$(uname -s)" == Darwin ]]; then
    if [[ ! -d /Applications/Zotero.app && ! -d "$HOME/Applications/Zotero.app" ]]; then
      if command -v brew >/dev/null 2>&1; then brew install --cask zotero; else open_url 'https://www.zotero.org/download'; fi
    fi
    open -a Zotero || true
  elif [[ "$WINDOWS" == 1 ]]; then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(cygpath -w "$SKILL_DIR/scripts/windows-zotero.ps1")" || warn '请从开始菜单打开 Zotero，或重跑安装。'
  else
    open_url 'https://www.zotero.org/download'
  fi
  step '登录 Zotero；在设置中开启本地 API、附件同步与自动下载。'
  guide zotero_local
  guide zotero_sync
  pause '完成后回车检查'
  verify_step zotero-local || warn 'Desktop 尚未连接。'
  verify_step zotero-sync || warn '附件同步尚未就绪。'
else
  note '跳过本次配置；云端写入不依赖 Desktop。'
fi
pause

stage "可选：浏览器机构全文"
if confirm '配置 Kimi 浏览器连接'; then
  persist SETUP_BROWSER 1
  if [[ "$DEMO" == 1 ]]; then
    note '[模拟] 检查 daemon，缺失则安装，然后启动。'
  else
    KIMI_BIN="$(command -v kimi-webbridge || true)"
    KIMI_BIN="${KIMI_BIN:-$HOME/.kimi-webbridge/bin/kimi-webbridge}"
    if [[ "$WINDOWS" == 1 && -x "$HOME/.kimi-webbridge/bin/kimi-webbridge.exe" ]]; then KIMI_BIN="$HOME/.kimi-webbridge/bin/kimi-webbridge.exe"; fi
    if [[ "$WINDOWS" == 1 && ! -x "$KIMI_BIN" ]]; then
      open_url 'https://www.kimi.com/products/kimi-webbridge'
      step '按页面的 Windows 安装说明安装连接服务。'
      pause '安装完成后回车'
      KIMI_BIN="$HOME/.kimi-webbridge/bin/kimi-webbridge.exe"
    elif [[ ! -x "$KIMI_BIN" ]]; then
      installer="$(mktemp)"
      if curl -fsSL https://cdn.kimi.com/webbridge/install.sh -o "$installer"; then bash "$installer"; fi
      rm -f "$installer"
    fi
    "$KIMI_BIN" start || warn '连接服务尚未启动，稍后可重跑配置。'
  fi
  open_url 'https://www.kimi.ai/products/kimi-webbridge'
  step '安装并启用浏览器扩展，授权连接；机构访问还需登录机构账号。'
  pause '完成后回车检查'
  verify_step kimi || warn '浏览器尚未连接。'
else
  note '已跳过；可直接下载的全文不需要浏览器。'
fi
pause

stage "总检"
if [[ "$DEMO" == 1 ]]; then
  note '[模拟检查通过] 正式版会验证核心服务及选中的可选功能。'
  pause '回车查看演示结果'
  finish
  warn '以上结果均为模拟，不代表真实环境就绪；临时配置即将删除。'
else
  if "$PYTHON_BIN" "$SKILL_DIR/scripts/configure.py" --check; then
    pause '检查通过，回车查看结果'
    finish
  else
    warn '部分配置尚未完成；已填写内容保留，重跑 setup 即可继续。'
    exit 1
  fi
fi
